export const generalAppState = {
  token: null,
  isCollapsed: false,
  isLoggedIn: false,
  isLoading: false,
  isCreateTaskModalOpen: false,
  isCreatingTask: false,
  taskType: null,
  teams: [],
  userTeams: [],
  teamId: null,
  staffId: null,
  isAdmin: false,
  rejectionReason: "",
  showModal: false,
};
